### ISSUE TITLE
Cannot build,some errors

### ISSUE THREAD

**Issue by qianlicao8000** [Rejdok/STM32-Marlin-Port#1]
Hi,I noticed the marlin port,I down it .When build,some warnings below.Is it a workable project on reprap 3d printer?

Description	Resource	Path	Location	Type
"LCD_ALERTMESSAGEPGM" redefined	ultralcd.h	/MarlinPort/Marlin/Include	line 166	C/C++ Problem

**Comment by Rejdok** [comment]
Hello, sorry for long answer, and my bad english. How you build it?

**Comment by Rejdok** [comment]
You should install sw4stm32, open project, then build. Sorry, but makefile dosen't work.

**Comment by qianlicao8000** [comment]
Ok,copy that.I solved the problem.
