### ISSUE TITLE
I think a typo in the file "tim.c" port stm32f1xx

### ISSUE THREAD

**Issue by bsamen** [Rejdok/STM32-Marlin-Port#5]
Hi.
I think a typo in the file "tim.c" port stm32f1xx. 
Timer settings must be N-1:
for example, in line 68 need to replace  " TimerHeaterAndPwm.Init.Prescaler = 36;" 
on " TimerHeaterAndPwm.Init.Prescaler = 36-1;"
in line 70 need to replace "TimerHeaterAndPwm.Init.Period = 2000;"
on "TimerHeaterAndPwm.Init.Period = 2000-1;"
also need to fix the line 100, 102 and 131.

**Comment by Rejdok** [comment]
Yes, you are right. But I won't fix that now, sorry.
