### ISSUE TITLE
Распиновка

### ISSUE THREAD

**Issue by neurotoxin78** [Rejdok/STM32-Marlin-Port#6]
Добрый вечер. Не могу понять где мне найти распиновку для stm32f103.
Нашел только X, Y, Z, E0, E1, Heater0 и FAN. А куда подключать второй нагреватель, а термисторы, хотбэд и концевики ? Где посмотреть все эти пины?

**Comment by Rejdok** [comment]
Здравствуйте! Их нужно задать вручную в файлах port.cpp и pins_port.h. В первом на нужную фичу нужно повесить индекс, который соответствует элементу(порту/пину) массива pinMap. В pinMap добавить нужный порт/пин.
