### ISSUE TITLE
работает ли под stm32f103rbt6 на дельте?

### ISSUE THREAD

**Issue by whoim2** [Rejdok/STM32-Marlin-Port#7]
Ищу с чем бы поковыряться на проприетарном принтере..

**Comment by Rejdok** [comment]
Добрый день, давненько не заглядывал на github. На дельте будет работать с правильными настройками. Но лучше взять оригинальный марлин 2.0. Его, кажется, уже портировали на stm32f103.

**Comment by whoim2** [comment]
Искал для ezt-t1, там под 2.0 марлин мало 128кб. Уже давно нет того принтера, а я на клиппере)
